query getMovieById($movieId: Int!){
  movieDetail(id: $movieId) {
    movie {
        original_title
        overview
        poster_path
        genres {
          id
          name
        }
    }
  }
}