query getMovieById($movieId: Int!){
  movieDetail(id: $movieId) {
    movie {
        original_title
        overview
        poster_path
        genres {
          id
          name
        }
    }
  }
}

query getLatestReleases{
  nowPlayingMovies {
    movies{
      id
      release_date
    }
  }
  popularMovies {
    movies{
      id
      release_date
    }
  }
}