query getMovieById($movieId: Int!){
  movieDetail(id: $movieId) {
      id
      title
      overview
      poster_path
      vote_average
      genres {
        id
        name
      }
  }
}

query getAvailableMovies{
  nowPlayingMovies {
    id
    release_date
  }
  popularMovies {
    id
    release_date
  }
}

query GetMovieDetails($movieId: Int!) {
  movieDetail(id: $movieId) {
      backdrop_path
      title
      overview
      poster_path
      release_date
      genres {
        id
        name
      }
      production_companies {
        id
        name
      }
  }
}

query getSimilarMovies($movieId: Int!){
  similarMovies (id: $movieId) {
      id
  }
}

query getPopularMovies{
  popularMovies{
    id
  }
}
#Error while trying to get the movies genres into nowPlayingMovies query and popularMovies query
#[GraphQL error]: Message: Cannot return null for non-nullable field Movie.genres.
#Location: [object Object], Path: nowPlayingMovies,movies,0,genres
# query GetGenresForMovies{
#   nowPlayingMovies {
#     movies{
#       id
#       genres {
#         id
#         name
#       }
#     }
#   }
#   popularMovies {
#     movies{
#       id
#       genres {
#         id
#         name
#       }
#     }
#   }
# }